# Generated by Django 5.0.6 on 2024-07-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_image_post_images_delete_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
