# Generated by Django 5.0.6 on 2024-07-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
