# Generated by Django 5.0.6 on 2024-07-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_remove_post_images_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(blank=True, null=True, upload_to='post_resources/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='res',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_res', to='social.postres'),
        ),
    ]
